name: Library CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build and test
        run: ./gradlew clean build test dokkaGeneratePublicationJavadoc
      - name: Upload library artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openhardwaremonitor-web-client-artifacts
          path: |
            build/libs/*
            build/publications/**
